#Install the Kaggle dataset

In [ ]:
!pip install kagglehub pandas

import kagglehub
from pathlib import Path


# Cosmetic brand products dataset (catalog)
products_path = Path(kagglehub.dataset_download("shivd24coder/cosmetic-brand-products-dataset"))
print("Products dataset path:", products_path)
print("Products contents:", list(products_path.iterdir())[:10])

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.2.25)
Downloading to /root/.cache/kagglehub/datasets/shivd24coder/cosmetic-brand-products-dataset/1.archive...

100%|██████████| 645k/645k [00:00<00:00, 97.3MB/s]

Extracting files...
Products dataset path: /root/.cache/kagglehub/datasets/shivd24coder/cosmetic-brand-products-dataset/versions/1
Products contents: [PosixPath('/root/.cache/kagglehub/datasets/shivd24coder/cosmetic-brand-products-dataset/versions/1/makeup_data.json'), PosixPath('/root/.cache/kagglehub/datasets/shivd24coder/cosmetic-brand-products-dataset/versions/1/output.csv')]

In [ ]:
import os

print(products_path)
print(os.listdir(products_path))

/root/.cache/kagglehub/datasets/shivd24coder/cosmetic-brand-products-dataset/versions/1
['makeup_data.json', 'output.csv']

#Show the dataset

In [ ]:
import pandas as pd

products_csv = products_path / "output.csv"
products_df = pd.read_csv(products_csv)

print(products_df.head())

     id      brand                  name  price price_sign currency  \
0  1048  colourpop         Lippie Pencil    5.0          $      CAD
1  1047  colourpop           Blotted Lip    5.5          $      CAD
2  1046  colourpop           Lippie Stix    5.5          $      CAD
3  1045  colourpop  No Filter Foundation   12.0          $      CAD
4  1044      boosh              Lipstick   26.0          $      CAD

                                          image_link  \
0  https://cdn.shopify.com/s/files/1/1338/0845/co...
1  https://cdn.shopify.com/s/files/1/1338/0845/pr...
2  https://cdn.shopify.com/s/files/1/1338/0845/co...
3  https://cdn.shopify.com/s/files/1/1338/0845/pr...
4  https://cdn.shopify.com/s/files/1/1016/3243/pr...

                                        product_link  \
0    https://colourpop.com/collections/lippie-pencil
1  https://colourpop.com/collections/lippie-stix?...
2      https://colourpop.com/collections/lippie-stix
3  https://colourpop.com/products/no-filter-matte...
4               https://www.boosh.ca/collections/all

                                        website_link  \
0                              https://colourpop.com
1                              https://colourpop.com
2                              https://colourpop.com
3  https://colourpop.com/products/no-filter-matte...
4                              https://www.boosh.ca/

                                         description  rating  category  \
0  Lippie Pencil A long-wearing and high-intensit...     NaN    pencil
1  Blotted Lip Sheer matte lipstick that creates ...     NaN  lipstick
2  Lippie Stix Formula contains Vitamin E, Mango,...     NaN  lipstick
3  Developed for the Selfie Age, our buildable fu...     NaN    liquid
4  All of our products are free from lead and hea...     NaN  lipstick

  product_type                      tag_list                created_at  \
0    lip_liner     ['cruelty free', 'Vegan']  2018-07-08T23:45:08.056Z
1     lipstick     ['cruelty free', 'Vegan']  2018-07-08T22:01:20.178Z
2     lipstick     ['cruelty free', 'Vegan']  2018-07-08T21:47:49.858Z
3   foundation     ['cruelty free', 'Vegan']  2018-07-08T18:22:25.273Z
4     lipstick  ['Chemical Free', 'Organic']  2018-07-08T17:32:28.088Z

                 updated_at  \
0  2018-07-09T00:53:23.301Z
1  2018-07-09T00:53:23.287Z
2  2018-07-09T00:53:23.274Z
3  2018-07-09T00:53:23.313Z
4  2018-09-02T22:52:06.669Z

                                     product_api_url  \
0  http://makeup-api.herokuapp.com/api/v1/product...
1  http://makeup-api.herokuapp.com/api/v1/product...
2  http://makeup-api.herokuapp.com/api/v1/product...
3  http://makeup-api.herokuapp.com/api/v1/product...
4  http://makeup-api.herokuapp.com/api/v1/product...

                                  api_featured_image  \
0  //s3.amazonaws.com/donovanbailey/products/api_...
1  //s3.amazonaws.com/donovanbailey/products/api_...
2  //s3.amazonaws.com/donovanbailey/products/api_...
3  //s3.amazonaws.com/donovanbailey/products/api_...
4  //s3.amazonaws.com/donovanbailey/products/api_...

                                      product_colors
0  [{'hex_value': '#B28378', 'colour_name': 'BFF ...
1  [{'hex_value': '#b72227', 'colour_name': "Bee'...
2  [{'hex_value': '#F2DEC3', 'colour_name': 'Fair...
3  [{'hex_value': '#F2DEC3', 'colour_name': 'Fair...
4  [{'hex_value': '#CB4975', 'colour_name': 'Babs...

#Data Cleaning

Drop ["created_at", "updated_at", "product_api_url", "api_featured_image"]

In [ ]:
cols_to_drop = ["created_at", "updated_at", "product_api_url", "api_featured_image"]

clean_products_df = products_df.drop(columns=cols_to_drop, errors="ignore")
clean_products_df.head()

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,product_colors
0,1048,colourpop,Lippie Pencil,5.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-pencil,https://colourpop.com,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']","[{'hex_value': '#B28378', 'colour_name': 'BFF ..."
1,1047,colourpop,Blotted Lip,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/collections/lippie-stix?...,https://colourpop.com,Blotted Lip Sheer matte lipstick that creates ...,NaN,lipstick,lipstick,"['cruelty free', 'Vegan']","[{'hex_value': '#b72227', 'colour_name': ""Bee'..."
2,1046,colourpop,Lippie Stix,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-stix,https://colourpop.com,"Lippie Stix Formula contains Vitamin E, Mango,...",NaN,lipstick,lipstick,"['cruelty free', 'Vegan']","[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
3,1045,colourpop,No Filter Foundation,12.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/products/no-filter-matte...,https://colourpop.com/products/no-filter-matte...,"Developed for the Selfie Age, our buildable fu...",NaN,liquid,foundation,"['cruelty free', 'Vegan']","[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
4,1044,boosh,Lipstick,26.0,$,CAD,https://cdn.shopify.com/s/files/1/1016/3243/pr...,https://www.boosh.ca/collections/all,https://www.boosh.ca/,All of our products are free from lead and hea...,NaN,lipstick,lipstick,"['Chemical Free', 'Organic']","[{'hex_value': '#CB4975', 'colour_name': 'Babs..."

Drop empty colours rows

In [ ]:
empty_colors = clean_products_df[clean_products_df["product_colors"].astype(str).str.strip() == "[]"]

print(len(empty_colors), "rows with empty product_colors")
empty_colors.head()

239 rows with empty product_colors

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,product_colors
50,998,nyx,Fly With Me Mascara,9.0,$,USD,https://www.nyxcosmetics.com/dw/image/v2/AANG_...,https://www.nyxcosmetics.com/fly-with-me-masca...,https://www.nyxcosmetics.com,Your lashes will reach new heights with our Fl...,NaN,NaN,mascara,[],[]
51,997,nyx,Propel My Eyes Mascara,9.0,$,USD,https://www.nyxcosmetics.com/dw/image/v2/AANG_...,https://www.nyxcosmetics.com/propel-my-eyes-ma...,https://www.nyxcosmetics.com,Get ready for aerodynamic lashes! The brush bo...,NaN,NaN,mascara,[],[]
52,996,nyx,Proof It! Waterproof Mascara Top Coat,7.0,$,USD,https://www.nyxcosmetics.com/dw/image/v2/AANG_...,https://www.nyxcosmetics.com/proof-it-waterpro...,https://www.nyxcosmetics.com,With just two swipes our lash top coat transfo...,NaN,NaN,mascara,[],[]
53,995,nyx,Big & Loud Lash Primer,7.0,$,USD,https://www.nyxcosmetics.com/dw/image/v2/AANG_...,https://www.nyxcosmetics.com/big-and-loud-lash...,https://www.nyxcosmetics.com,Give your lashes a boost with our Big & Loud L...,NaN,NaN,mascara,[],[]
54,994,nyx,Double Stacked Mascara,15.0,$,USD,https://www.nyxcosmetics.com/dw/image/v2/AANG_...,https://www.nyxcosmetics.com/double-stacked-ma...,https://www.nyxcosmetics.com,NaN,NaN,NaN,mascara,[],[]

In [ ]:
# Remove rows where product_colors is "[]" or NaN
clean_products_df = clean_products_df[
    ~(clean_products_df["product_colors"].astype(str).str.strip() == "[]")
    & ~clean_products_df["product_colors"].isna()
]

print(f"Remaining products: {len(clean_products_df)}")
clean_products_df.head()

Remaining products: 692

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,product_colors
0,1048,colourpop,Lippie Pencil,5.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-pencil,https://colourpop.com,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']","[{'hex_value': '#B28378', 'colour_name': 'BFF ..."
1,1047,colourpop,Blotted Lip,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/collections/lippie-stix?...,https://colourpop.com,Blotted Lip Sheer matte lipstick that creates ...,NaN,lipstick,lipstick,"['cruelty free', 'Vegan']","[{'hex_value': '#b72227', 'colour_name': ""Bee'..."
2,1046,colourpop,Lippie Stix,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-stix,https://colourpop.com,"Lippie Stix Formula contains Vitamin E, Mango,...",NaN,lipstick,lipstick,"['cruelty free', 'Vegan']","[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
3,1045,colourpop,No Filter Foundation,12.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/products/no-filter-matte...,https://colourpop.com/products/no-filter-matte...,"Developed for the Selfie Age, our buildable fu...",NaN,liquid,foundation,"['cruelty free', 'Vegan']","[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
4,1044,boosh,Lipstick,26.0,$,CAD,https://cdn.shopify.com/s/files/1/1016/3243/pr...,https://www.boosh.ca/collections/all,https://www.boosh.ca/,All of our products are free from lead and hea...,NaN,lipstick,lipstick,"['Chemical Free', 'Organic']","[{'hex_value': '#CB4975', 'colour_name': 'Babs..."

See remaining products

In [ ]:
import ast

rows = []
for _, row in clean_products_df.iterrows():
    colors = row.get("product_colors")
    try:
        colors_list = ast.literal_eval(colors)
    except (ValueError, SyntaxError):
        continue

    for c in colors_list:
        rows.append({
            "id": row["id"],
            "brand": row["brand"],
            "name": row["name"],
            "product_type": row["product_type"],
            "hex": c["hex_value"].lstrip("#"),
            "shade_name": c["colour_name"],
        })

catalog_df = pd.DataFrame(rows)
print(f"Total shades in catalog: {len(catalog_df)}")
catalog_df.head()

Total shades in catalog: 5329

     id      brand           name product_type     hex      shade_name
0  1048  colourpop  Lippie Pencil    lip_liner  B28378      BFF Pencil
1  1048  colourpop  Lippie Pencil    lip_liner  A36B5E      951 Pencil
2  1048  colourpop  Lippie Pencil    lip_liner  966A60   Beeper Pencil
3  1048  colourpop  Lippie Pencil    lip_liner  8F5954  Oh Snap Pencil
4  1048  colourpop  Lippie Pencil    lip_liner  975348   Curvii Pencil

Show the dataset with the columns that I am going to use

In [ ]:
selected_cols = ["id", "brand", "name", "price", "price_sign", "currency",
                 "product_link", "description", "product_colors"]

clean_products_df[selected_cols].head()

,id,brand,name,price,price_sign,currency,product_link,description,product_colors
0,1048,colourpop,Lippie Pencil,5.0,$,CAD,https://colourpop.com/collections/lippie-pencil,Lippie Pencil A long-wearing and high-intensit...,"[{'hex_value': '#B28378', 'colour_name': 'BFF ..."
1,1047,colourpop,Blotted Lip,5.5,$,CAD,https://colourpop.com/collections/lippie-stix?...,Blotted Lip Sheer matte lipstick that creates ...,"[{'hex_value': '#b72227', 'colour_name': ""Bee'..."
2,1046,colourpop,Lippie Stix,5.5,$,CAD,https://colourpop.com/collections/lippie-stix,"Lippie Stix Formula contains Vitamin E, Mango,...","[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
3,1045,colourpop,No Filter Foundation,12.0,$,CAD,https://colourpop.com/products/no-filter-matte...,"Developed for the Selfie Age, our buildable fu...","[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
4,1044,boosh,Lipstick,26.0,$,CAD,https://www.boosh.ca/collections/all,All of our products are free from lead and hea...,"[{'hex_value': '#CB4975', 'colour_name': 'Babs..."

#Show NaN Values

In [ ]:
# 1. Summary table: count and percentage of NaN per column
nan_summary = pd.DataFrame({
    "nan_count":   clean_products_df.isna().sum(),
    "nan_percent": (clean_products_df.isna().mean() * 100).round(2)
})
nan_summary = nan_summary[nan_summary["nan_count"] > 0].sort_values("nan_percent", ascending=False)
print("=== Columns with NaN values ===")
print(nan_summary.to_string())

# 2. Rows where key business columns are NaN
important_cols = ["brand", "name", "price", "rating", "product_type", "category", "description"]
print("\n=== NaN counts in important columns ===")
for col in important_cols:
    n = clean_products_df[col].isna().sum()
    if n:
        print(f"  {col}: {n} NaN rows")
        print(clean_products_df[clean_products_df[col].isna()][["id", "brand", "name", "price", "product_type"]].head(3).to_string(index=False))
        print()

# 3. Rows with ANY NaN across all columns
rows_with_any_nan = clean_products_df[clean_products_df.isna().any(axis=1)]
print(f"=== Rows with at least one NaN: {len(rows_with_any_nan)} / {len(clean_products_df)} ===")
print(rows_with_any_nan[important_cols].head(10).to_string())

=== Columns with NaN values ===
             nan_count  nan_percent
rating             466        67.34
currency           358        51.73
price_sign         358        51.73
category           314        45.38
description         21         3.03
price               10         1.45
brand                8         1.16

=== NaN counts in important columns ===
  brand: 8 NaN rows
 id brand                     name  price product_type
507   NaN  Saint Cosmetics Bronzer  30.96      bronzer
494   NaN Fake Bake Beauty Bronzer  21.00      bronzer
469   NaN    Saint Cosmetics Blush  28.96        blush

  price: 10 NaN rows
 id    brand                                     name  price product_type
772 clinique Clinique Pop&trade; Oil Lip & Cheek Glow    NaN        blush
657     iman             Cover Cream Clay Medium Deep    NaN   foundation
656     iman                Corrective Concealer Clay    NaN   foundation

  rating: 466 NaN rows
  id     brand          name  price product_type
1048 colourpop Lippie Pencil    5.0    lip_liner
1047 colourpop   Blotted Lip    5.5     lipstick
1046 colourpop   Lippie Stix    5.5     lipstick

  category: 314 NaN rows
  id                  brand                               name  price product_type
1040   zorah biocosmetiques                          Eyeshadow    0.0    eyeshadow
1038 sally b's skin yummies                          B Smudged    0.0    eyeshadow
1036        rejuva minerals Multi Purpose Powder - Blush & Eye    0.0    eyeshadow

  description: 21 NaN rows
  id                 brand                                  name  price product_type
1019 maia's mineral galaxy Mineral Eye Brow Liner Charcoal Brown    0.0      eyebrow
 984                   nyx             3-Dimensional Brow Marker   10.0      eyebrow
 982                   nyx              Build 'Em Up Brow Powder    8.0      eyebrow

=== Rows with at least one NaN: 692 / 692 ===
                  brand                               name  price  rating product_type  category                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           description
0             colourpop                      Lippie Pencil    5.0     NaN    lip_liner    pencil                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Lippie Pencil A long-wearing and high-intensity lip pencil that glides on easily and prevents feathering. Many of our Lippie Stix have a coordinating Lippie Pencil designed to compliment it perfectly, but feel free to mix and match!
1             colourpop                        Blotted Lip    5.5     NaN     lipstick  lipstick                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Blotted Lip Sheer matte lipstick that creates the perfect popsicle pout! Formula is lightweight, matte and buildable for light to medium coverage.
2             colourpop                        Lippie Stix    5.5     NaN     lipstick  lipstick                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Lippie Stix Formula contains Vitamin E, Mango, Avocado, and Shea butter for added comfort and moisture. None of our Lippie formulas contain any nasty ingredients like Parabens or Sulfates.
3             colourpop               No Filter Foundation   12.0     NaN   foundation    liquid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Developed for the Selfie Age, our buildable full coverage, natural matte foundation delivers flawless looking skin from day-to-night. The oil-free, lightweight formula blends smoothly and is easily customizable to create the coverage you want. Build it up or sheer it out, it was developed with innovative soft-blurring pigments to deliver true color while looking and feeling natural. The lockable pump is easy to use and keeps your routine mess-free! As always, 100% cruelty-free and vegan.
4                 boosh                           Lipstick   26.0     NaN     lipstick  lipstick                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 All of our products are free from lead and heavy metals, parabens, phthalates, artificial colourants, and synthetic fragrances.  Boosh lipstick glides on smoothly for clean & protective SPF coverage. They are filled with hydrating oils and butters to preserve and enhance your lips natural surface. Organic sweet orange oil gives a light and cheerful scent.
5                deciem                   Serum Foundation    6.7     NaN   foundation    liquid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Serum Foundations are lightweight medium-coverage formulations available in a comprehensive shade range across 21 shades. These foundations offer moderate coverage that looks natural with a very lightweight serum feel. They are very low in viscosity and are dispensed with the supplied pump or with the optional glass dropper available for purchase separately if preferred.
6                deciem                Coverage Foundation    6.9     NaN   foundation    liquid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Coverage Foundations are full-coverage formulations available in a comprehensive shade range across 21 shades. These foundations contain higher pigment levels than our Serum Foundations but still offer a smooth finish that avoids the heavy makeup look that can make skin appear more aged. The texture is that of a lightweight, non-oily cream.
7  zorah biocosmetiques                       Liquid Liner    0.0     NaN     eyeliner    liquid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <strong>12 hours of long-lasting</strong> intense color, transfer-free (leaves no trace on crease above the eyelid) <strong>Pure Light Capture®</strong> <strong>minerals</strong> deliver color and radiance. Silky lines and refreshingly light, Pure Argan eyeliner leaves a weightless feel on the eyelids.<p align='LEFT'>Natural cosmetic certified by Ecocert Greenlife according to Ecocert Standard available at: http://cosmetiques.ecocert.com</p>98% of the total ingredients are from natural origin 5% of total ingredients are from organic farming
8  zorah biocosmetiques                          Eyeshadow    0.0     NaN    eyeshadow       NaN                                                                                                                                                                                                                                                                                                       <strong>Product Description</strong>Anti-aging formula made with organic Pure Argan oil and Pure Light Capture<sup>®</sup> pigments. 24 Hour crease-free intensity (no build-up increase of eyelid), no running. Pure Light Capture® pigments deliver color and luminosity. Silky and refreshingly light feel, Pure Argan eyeshadow is weightless on the eyelids. Pure Argan eyeshadow <strong>soothes</strong>, <strong>hides redness </strong>and <strong>slows the appearance of the signs of aging on the skin.</strong><p align='LEFT'>Natural cosmetic certified by Ecocert Greenlife according to Ecocert Standard available at: http://cosmetiques.ecocert.com</p>100% of the total ingredients are from natural origin5% of total ingredients are from organic farming
9            w3llpeople   Realist Invisible Setting Powder    0.0     NaN   foundation    powder  <span style="font-weight: 400;">Keep it real with a polished, soft-focus look using this superfine, loose mineral powder. The healing properties of organic aloe help soothe and calm stressed out skin. Instantly minimize pores, soften imperfections, and creates a matte finish with superfine powder. Use by itself for an air-brushed look, or to set foundation for ultra-long wear.</span><span style="font-weight: 400;">* Set makeup or by itself for matte air-brushed effect</span><span style="font-weight: 400;">* Absorbs excess oil while softening fine lines</span><span style="font-weight: 400;">* Organic aloe creates radiant, rejuvenated skin</span><span style="font-weight: 400;">* Hypoallergenic, Chemical Free, Cruelty Free &amp; Noncomedogenic </span><span style="font-weight: 400;">* EWG Verified for non-toxic health and safety</span><span style="font-weight: 400;">* Free From: Parabens, Gluten, GMO, Phthalates, Sulfates, Fragrance, Pheonoxyethanol, Dimethicone, PEG, Propylene Glycol, Butylene Glycol, Lead, Mineral Oil, Talc</span>

Drop Nan Values and fill more columns

In [ ]:
import pandas as pd
import re

# ── 1. Drop NaN brand (8 rows) ─────────────────────────────────────────────
clean_products_df = clean_products_df.dropna(subset=["brand"])

# ── 2. Fill currency / price_sign with defaults ────────────────────────────
clean_products_df["price_sign"] = clean_products_df["price_sign"].fillna("$")
clean_products_df["currency"]   = clean_products_df["currency"].fillna("USD")

# ── 3. Remove nail polish ──────────────────────────────────────────────────
nail_polish_mask = (
    clean_products_df["product_type"].str.contains("nail", case=False, na=False) |
    clean_products_df["category"].str.contains("nail", case=False, na=False) |
    clean_products_df["name"].str.contains("nail polish", case=False, na=False)
)
clean_products_df = clean_products_df[~nail_polish_mask]

# ── 4. Strip HTML from description, fill remaining NaN with "" ─────────────
def strip_html(text):
    if pd.isna(text):
        return ""
    return re.sub(r"<[^>]+>", "", str(text)).strip()

clean_products_df["description"] = clean_products_df["description"].apply(strip_html)

# ── 5. Drop NaN price (10 rows) ────────────────────────────────────────────
clean_products_df = clean_products_df.dropna(subset=["price"])

# ── 6. Fill category with product_type where missing ──────────────────────
clean_products_df["category"] = clean_products_df["category"].fillna(
    clean_products_df["product_type"]
)

# ── 7. Drop rating (67% NaN — not reliable) ────────────────────────────────
clean_products_df = clean_products_df.drop(columns=["rating"])

# ── 8. Summary ─────────────────────────────────────────────────────────────
print(f"Final dataset: {len(clean_products_df)} rows")
print(f"Columns: {list(clean_products_df.columns)}\n")
print("=== Remaining NaN ===")
remaining = clean_products_df.isna().sum()
remaining = remaining[remaining > 0]
print(remaining if not remaining.empty else "None — dataset is clean!")

Final dataset: 630 rows
Columns: ['id', 'brand', 'name', 'price', 'price_sign', 'currency', 'image_link', 'product_link', 'website_link', 'description', 'category', 'product_type', 'tag_list', 'product_colors']

=== Remaining NaN ===
None — dataset is clean!

#Reassign the ID column

In [ ]:
clean_products_df = clean_products_df.reset_index(drop=True)
clean_products_df["id"] = clean_products_df.index + 1

print(f"New id range: {clean_products_df['id'].min()} → {clean_products_df['id'].max()}")
clean_products_df[["id", "brand", "name"]].head()

New id range: 1 → 630

   id      brand                  name
0   1  colourpop         Lippie Pencil
1   2  colourpop           Blotted Lip
2   3  colourpop           Lippie Stix
3   4  colourpop  No Filter Foundation
4   5      boosh              Lipstick

# Final dataset overview

In [ ]:
print(f"Shape: {clean_products_df.shape}")
print(f"\nColumn dtypes:\n{clean_products_df.dtypes}")
print(f"\nNaN check:\n{clean_products_df.isna().sum()}")
print(f"\nSample rows:")
clean_products_df.head(10)

Shape: (630, 14)

Column dtypes:
id                  int64
brand              object
name               object
price             float64
price_sign         object
currency           object
image_link         object
product_link       object
website_link       object
description        object
category           object
product_type       object
tag_list           object
product_colors     object
dtype: object

NaN check:
id                0
brand             0
name              0
price             0
price_sign        0
currency          0
image_link        0
product_link      0
website_link      0
description       0
category          0
product_type      0
tag_list          0
product_colors    0
dtype: int64

Sample rows:

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,category,product_type,tag_list,product_colors
0,1,colourpop,Lippie Pencil,5.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-pencil,https://colourpop.com,Lippie Pencil A long-wearing and high-intensit...,pencil,lip_liner,"['cruelty free', 'Vegan']","[{'hex_value': '#B28378', 'colour_name': 'BFF ..."
1,2,colourpop,Blotted Lip,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/collections/lippie-stix?...,https://colourpop.com,Blotted Lip Sheer matte lipstick that creates ...,lipstick,lipstick,"['cruelty free', 'Vegan']","[{'hex_value': '#b72227', 'colour_name': ""Bee'..."
2,3,colourpop,Lippie Stix,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-stix,https://colourpop.com,"Lippie Stix Formula contains Vitamin E, Mango,...",lipstick,lipstick,"['cruelty free', 'Vegan']","[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
3,4,colourpop,No Filter Foundation,12.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/products/no-filter-matte...,https://colourpop.com/products/no-filter-matte...,"Developed for the Selfie Age, our buildable fu...",liquid,foundation,"['cruelty free', 'Vegan']","[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
4,5,boosh,Lipstick,26.0,$,CAD,https://cdn.shopify.com/s/files/1/1016/3243/pr...,https://www.boosh.ca/collections/all,https://www.boosh.ca/,All of our products are free from lead and hea...,lipstick,lipstick,"['Chemical Free', 'Organic']","[{'hex_value': '#CB4975', 'colour_name': 'Babs..."
5,6,deciem,Serum Foundation,6.7,$,CAD,https://3bc01d2807fb1bc0d25c-a86d2521f1af89898...,https://deciem.com/product/rdn-serum-foundatio...,https://deciem.com/,Serum Foundations are lightweight medium-cover...,liquid,foundation,"['water free', 'cruelty free', 'alcohol free',...","[{'hex_value': '#f4e5d6', 'colour_name': '1.0P..."
6,7,deciem,Coverage Foundation,6.9,$,CAD,https://3bc01d2807fb1bc0d25c-a86d2521f1af89898...,https://deciem.com/product/rdn-coverage-founda...,https://deciem.com/,Coverage Foundations are full-coverage formula...,liquid,foundation,"['water free', 'cruelty free', 'alcohol free',...","[{'hex_value': '#f4e5d6', 'colour_name': '1.0P..."
7,8,zorah biocosmetiques,Liquid Liner,0.0,$,USD,https://www.purpicks.com/wp-content/uploads/20...,https://www.purpicks.com/product/zorah-biocosm...,https://purpicks.com/,"12 hours of long-lasting intense color, transf...",liquid,eyeliner,"['purpicks', 'EcoCert']","[{'hex_value': '#000000', 'colour_name': 'Blac..."
8,9,zorah biocosmetiques,Eyeshadow,0.0,$,USD,https://www.purpicks.com/wp-content/uploads/20...,https://www.purpicks.com/product/zorah-eyeshadow/,https://purpicks.com/,Product DescriptionAnti-aging formula made wit...,eyeshadow,eyeshadow,"['purpicks', 'EcoCert']","[{'hex_value': '#966A54', 'colour_name': 'Saha..."
9,10,w3llpeople,Realist Invisible Setting Powder,0.0,$,USD,https://www.purpicks.com/wp-content/uploads/20...,https://www.purpicks.com/product/w3llpeople-re...,https://purpicks.com/,"Keep it real with a polished, soft-focus look ...",powder,foundation,"['purpicks', 'EWG Verified', 'Gluten Free']","[{'hex_value': '#E8E6E7', 'colour_name': 'Tran..."

#Add a new column : undertone

In [ ]:
!pip install colormath -q

  Preparing metadata (setup.py) ... done
  Building wheel for colormath (setup.py) ... done

In [ ]:
import ast
from colormath.color_objects import sRGBColor, LabColor
from colormath.color_conversions import convert_color
import numpy as np

def hex_to_hue_angle(hex_str):
    hex_str = hex_str.strip().lstrip("#")
    r, g, b = int(hex_str[0:2],16)/255, int(hex_str[2:4],16)/255, int(hex_str[4:6],16)/255
    rgb = sRGBColor(r, g, b)
    lab = convert_color(rgb, LabColor)
    return np.degrees(np.arctan2(lab.lab_b, lab.lab_a)) % 360

def assign_undertone(product_colors_str):
    try:
        colors_list = ast.literal_eval(product_colors_str)
    except (ValueError, SyntaxError):
        return "neutral"

    angles = []
    for c in colors_list:
        try:
            angles.append(hex_to_hue_angle(c["hex_value"]))
        except Exception:
            continue

    if not angles:
        return "neutral"

    avg_angle = np.mean(angles)

    if avg_angle > 60:
        return "warm"
    elif avg_angle < 60:
        return "cool"
    else:
        return "neutral"

# ── Add undertone column ───────────────────────────────────────────────────
clean_products_df["undertone"] = clean_products_df["product_colors"].apply(assign_undertone)

print(clean_products_df["undertone"].value_counts())
clean_products_df[["brand", "name", "product_type", "undertone"]].head(10)

undertone
warm       374
cool       252
neutral      4
Name: count, dtype: int64

,brand,name,product_type,undertone
0,colourpop,Lippie Pencil,lip_liner,warm
1,colourpop,Blotted Lip,lipstick,cool
2,colourpop,Lippie Stix,lipstick,warm
3,colourpop,No Filter Foundation,foundation,warm
4,boosh,Lipstick,lipstick,warm
5,deciem,Serum Foundation,foundation,warm
6,deciem,Coverage Foundation,foundation,warm
7,zorah biocosmetiques,Liquid Liner,eyeliner,cool
8,zorah biocosmetiques,Eyeshadow,eyeshadow,warm
9,w3llpeople,Realist Invisible Setting Powder,foundation,warm

#Download products final Dataset

In [ ]:
from google.colab import files

clean_products_df.to_csv("products_catalog.csv", index=False)
files.download("products_catalog.csv")